#!/usr/bin/env python3
"""Rebuild reddit/BOARD.md from reddit/threads/*.md. Derived, never hand-edited.

One file per thread. Status lifecycle:
  seen -> queued (a draft exists in drafts/) -> replied | skipped
  watching (worth a second look later), fix (our own comment needs editing)

The board also prints a per-sub WATERMARK: the newest thread id we have seen.
Reddit ids are base36 and increase over time, so a sweep of /r/<sub>/new/
only needs to look at ids above the watermark to know what is new.
"""
import os, re
# Data lives in the content estate, code lives here (see reconcile.py).
HERE=os.path.abspath(os.environ.get('REDDIT_DESK') or os.path.expanduser('~/.claude/content/reddit'))
TD=os.path.join(HERE,'threads')
FIELDS=['Sub','Id','URL','Posted','First seen','Last checked','Status','Our reply','Product','Claims','Why']
def parse(p):
    t=open(p,encoding='utf-8').read()
    d={'title':(re.search(r'^# (.+)$',t,re.M) or [None,''])[1]}
    for f in FIELDS:
        m=re.search(r'^- \*\*%s:\*\* (.*)$'%re.escape(f),t,re.M)
        d[f]=m.group(1).strip() if m else ''
    d['file']=os.path.relpath(p,HERE)
    return d
rows=[parse(os.path.join(TD,f)) for f in sorted(os.listdir(TD)) if f.endswith('.md')]
rows.sort(key=lambda r:r['Posted'],reverse=True)
ORDER=[('fix','Fix first: our own comments that need editing'),('queued','To reply: a draft exists in drafts/'),('watching','Watching: read again before deciding'),('seen','Seen, not yet judged'),('replied','Replied'),('skipped','Skipped, with the reason')]
out=['# Reddit board','','**Generated by `reddit/reindex.py` from `reddit/threads/`. Do not hand-edit.**','Rules per sub: `RULES.md`. Every reply sent: `REPLY_LEDGER.md`. Drafts: `drafts/`.','The Claude artifact "Reddit Reply Desk" is a view of this file, never the record.','']
for st,label in ORDER:
    rs=[r for r in rows if r['Status']==st]
    out.append(f'## {label} ({len(rs)})'); out.append('')
    if not rs: out.append('(none)'); out.append(''); continue
    out.append('| Posted | Sub | Thread | Product | Claims | Why |'); out.append('| --- | --- | --- | --- | --- | --- |')
    for r in rs:
        link=f"[{r['title'][:70]}]({r['URL']})"
        rep=f" · [our reply]({r['Our reply']})" if r['Our reply'] not in ('','-') else ''
        out.append(f"| {r['Posted'][:10]} | {r['Sub']} | {link}{rep} | {r['Product']} | {r['Claims']} | {r['Why'][:140]} |")
    out.append('')
# watermarks
wm={}
for r in rows:
    i=r['Id']
    if re.fullmatch(r'[0-9a-z]{5,8}',i):
        v=int(i,36)
        if v>wm.get(r['Sub'],(0,''))[0]: wm[r['Sub']]=(v,i)
out.append('## Watermarks: newest thread id seen per sub'); out.append('')
out.append('A sweep of `/r/<sub>/new/` treats any id above this as new.'); out.append('')
out.append('| Sub | Newest id seen |'); out.append('| --- | --- |')
for s,(v,i) in sorted(wm.items()): out.append(f'| {s} | `{i}` |')
out.append('')
open(os.path.join(HERE,'BOARD.md'),'w',encoding='utf-8').write('\n'.join(out))
print(f'BOARD.md rebuilt: {len(rows)} threads, {len(wm)} subs')
